Перенос статики в корень рабочей папки
dizi-izi-plan/dizi-izi-backend pull request #101
Opened 2024-07-25 18:27 UTC by tenser-pit

2024-07-27 08:25 UTC, Srmrlt requested changes
Предлагаю исправить BASE_DIR и использовать абсолютный путь. Текущие изменения в целом правильные, но в дальнейшем могут привести к неверному расположению дирректории static

2024-07-27 09:37 UTC, tenser-pit commented
> Предлагаю исправить BASE_DIR и использовать абсолютный путь. Текущие изменения в целом правильные, но в дальнейшем могут привести к неверному расположению дирректории static

Сейчас как раз используется абсолютный путь т.е. корень проекта. Если использовать через BASE_DIR, то при изменении вложенности все опять сломается. Делаем через BASE_DIR?

2024-07-27 10:53 UTC, Srmrlt commented
> > Предлагаю исправить BASE_DIR и использовать абсолютный путь. Текущие изменения в целом правильные, но в дальнейшем могут привести к неверному расположению дирректории static
> 
> Сейчас как раз используется абсолютный путь т.е. корень проекта. Если использовать через BASE_DIR, то при изменении вложенности все опять сломается. Делаем через BASE_DIR?

Нее) У тебя сейчас как раз относительный путь. Причем относительно дирректории вызова команды, а не корня проекта. Если с твоими настройками сделать python ..\manage.py collectstatic будучи в папке config, то статика будет в config. Абсолютный путь от корня файловой системы. Да, если мы изменим вложенность проекта, то нужно будет менять base_dir, и об этом нужно помнить, возможно где-то в доках нужно это прописывать. Но это уже к вопросу качества изменений, и не влечет за собой случайных ошибок в случае изменения пути вызова проекта.

2024-07-29 11:28 UTC, tenser-pit commented
> > > Предлагаю исправить BASE_DIR и использовать абсолютный путь. Текущие изменения в целом правильные, но в дальнейшем могут привести к неверному расположению дирректории static
> > 
> > 
> > Сейчас как раз используется абсолютный путь т.е. корень проекта. Если использовать через BASE_DIR, то при изменении вложенности все опять сломается. Делаем через BASE_DIR?
> 
> Нее) У тебя сейчас как раз относительный путь. Причем относительно дирректории вызова команды, а не корня проекта. Если с твоими настройками сделать python ..\manage.py collectstatic будучи в папке config, то статика будет в config. Абсолютный путь от корня файловой системы. Да, если мы изменим вложенность проекта, то нужно будет менять base_dir, и об этом нужно помнить, возможно где-то в доках нужно это прописывать. Но это уже к вопросу качества изменений и не влечет за собой случайных ошибок в случае изменения пути вызова проекта.

Хорошо, путь поправил, жду пр))

2024-07-30 11:23 UTC, Srmrlt requested changes
В целом, рабочий вариант, но у нас останется неправильное определение BASE_DIR, что может быть проблемой в дальнейшем. Так что предлагаю поправить именно BASE_DIR.
И путь к media тоже будет правильный.

2024-07-30 18:18 UTC, Srmrlt approved these changes

2024-08-08 09:56 UTC, closed without merging