updating password, email validators
dizi-izi-plan/dizi-izi-backend pull request #111
Opened 2024-10-24 04:39 UTC by Pokatilov-s

Осталась проблема за двоения ошибки, при некоторых сценариях прогоняется стандартный валидатор, не критично, отловить пока не получилось.

2024-10-31 15:21 UTC, Srmrlt requested changes

2024-10-31 15:21 UTC, Srmrlt commented on users/validators/field_validators.py
Может стоит сделать комментарий для регулярки (32 строка)?

2024-10-31 15:21 UTC, Srmrlt commented on users/models.py
я не понял трюка с перехватом ValidationError и его же вызова

2024-10-31 15:21 UTC, Srmrlt commented on users/validators/password_validators.py
def get_help_text(self):
        return ""
  Нужно заполнить подсказки

2024-10-31 15:23 UTC, Srmrlt commented
> Осталась проблема за двоения ошибки, при некоторых сценариях прогоняется стандартный валидатор, не критично, отловить пока не получилось.

заведи как баг в кайтен

2024-11-05 12:48 UTC, Pokatilov-s commented on users/validators/field_validators.py
38 строке передаешь список сообщений, это не вызовет некорректное сообщение?

> 38 строке передаешь список сообщений, это не вызовет некорректное сообщение? 

Это вполне корректно обрабатывается, сделано для того чтобы ошибка выводилась более читабельно

2024-11-06 21:07 UTC, Srmrlt requested changes

2024-11-07 10:27 UTC, Srmrlt approved these changes

2024-11-07 10:30 UTC, merged